### ISSUE TITLE
Feedback footer displays in print view

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/service-manual-frontend#111] opened 2017-03-06 15:32 UTC
The footer feedback bar displays in print view - it probably shouldn't since you can't do anything with it.

Screenshot:
![screen shot 2017-03-06 at 11 14 19](https://cloud.githubusercontent.com/assets/2204224/23616552/06fd361c-0282-11e7-81e1-21a887347460.png)

Seen in Chrome 56.0.29

**Comment by 36degrees** [comment] 2017-03-06 16:30
I can't reproduce this – what URL are you seeing this on?

**Comment by edwardhorsford** [comment] 2017-03-06 16:34
Ah sorry, may be a bogus report.

Just realised it was on integration. I'd assume they'd work the same, but it looks like they don't?

**Comment by 36degrees** [comment] 2017-03-06 16:40
Whoops. Yep. Broken it as part of #110, which is currently on integration. Pushed a fix to that branch now. Thanks.

**Closed by 36degrees** 2017-03-06 16:40 UTC
